version: "3"
services:
  kafka1:
    build: .
    image: bdcloud/kafka
    hostname: kafka1
    container_name: kafka1
    restart: always
    extra_hosts:
      - "zoo1:192.168.31.86"
      - "zoo2:192.168.31.86"
      - "zoo3:192.168.31.86"
    volumes:
        - /etc/localtime:/etc/localtime
        - /opt/kafka:/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.31.86
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 0
  kafka2:
    image: bdcloud/kafka
    hostname: kafka2
    container_name: kafka2
    restart: always
    extra_hosts:
      - "zoo1:192.168.31.86"
      - "zoo2:192.168.31.86"
      - "zoo3:192.168.31.86"
    volumes:
        - /etc/localtime:/etc/localtime
        - /opt/kafka:/kafka
    ports:
      - "9093:9092"
    depends_on:
      - kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.31.86
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 1
  kafka3:
    image: bdcloud/kafka
    hostname: kafka3
    container_name: kafka3
    restart: always
    extra_hosts:
      - "zoo1:192.168.31.86"
      - "zoo2:192.168.31.86"
      - "zoo3:192.168.31.86"
    volumes:
        - /etc/localtime:/etc/localtime
        - /opt/kafka:/kafka
    ports:
      - "9094:9092"
    depends_on:
      - kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.31.86
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 2

